config/routes.rb
Askme::Application.routes.draw do
  get "home/index"
    get "sessions/create"
    get "sessions/destroy"
    get "welcome/index"
    
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    

    resources :sessions, only: [:create, :destroy]
    root 'home#index'

    resources :questions do
        resources :answers
        get :autocomplete_question_title, :on => :collection
    end
    
    resources :users, only: [:index] do
        get :autocomplete_user_name, :on => :collection 
    end

    resources :challenges
    resources :friendships, only: [:create, :destroy, :show, :update]

end

app/models/question.rb
class Question < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence:true
    validates :answerer_id, presence: true
    #validate :has_answers? # Has to disable this to provide copy question => bug to fix
    
    has_many :answers, dependent: :destroy
    accepts_nested_attributes_for :answers
    has_one :selectedAnswer, :class_name => 'Answer'
    
    belongs_to :answerer, :class_name => 'User', dependent: :destroy
    belongs_to :owner, :class_name => 'User', dependent: :destroy
    
    def has_answers?
        unless self.answers.size > 1
          self.errors[:question] << 'must have at least 2 answers'
        end
    end
    
    def answers_for_form
        collection = answers.where(question_id: id)
        collection.any? ? collection : answers.build
    end
    
    def self.search(query)
        # where(:title, query) -> This would return an exact match of the query
        where("title like ?", "%#{query}%") 
    end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    layout "application"
    autocomplete :question, :title
    
    def new
        @question = Question.new
        @user = current_user
        @friends = []
        for friendship in @user.friendships do
            @friends << User.find(friendship.friend)
        end
    end
    
    def create
        @question = Question.new(question_params)
        @question.owner_id = session[:user_id]
        @question.submitted = false
        answerer = User.where("name = ?", "#{params[:user_name]}").limit(1)
        @question.answerer = answerer[0]
        if @question.save
            redirect_to edit_question_path(@question)
        else
            render 'new'
        end
    end
    
    def show
        @question = Question.find(params[:id]) 
        @user = current_user
    end
    
    def index
        if params.has_key?(:question)
          @questions = Question.search(params[:question][:title]).order("created_at DESC")
        else
          @questions = Question.where(owner_id: current_user.id).order("created_at DESC")
        end
    end
    
    def edit
        @question = Question.find(params[:id])
        if @question.submitted
            redirect_to questions_path
        end
    end
    
    def update
        @question = Question.find(params[:id])
        @answer = Answer.find(params[:correct])
        @answer.correct = true
        @question.submitted = true;
        if @question.update(question_params) and @answer.save
            redirect_to @question
        else
            render 'edit'
        end 
    end
    
    def destroy
      @question = Question.find(params[:id])
      @question.destroy

      redirect_to questions_path
    end
    
    private
        def question_params
           params.require(:question).permit(:title, :content, :answerer_id,
               answers_attributes: [:id, :answer, :question_id, :correct, :_destroy]) 
        end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h1> Answer your question </h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>
    <label>From:</label> 
    <p class="challenge_owner">
        <%= @question.owner.name %>
    </p>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title, :class => "form_title" %>
    </p>

    <p>
        <%= f.label :content %><br>
        <%= f.text_area :content, :class => "form_content"  %>
    </p>

    <% @question.answers.each do |answer| %>
        <p>
            <%= radio_button_tag("correct", answer.id, answer.correct) %>
            <%= label_tag(:answer, answer.answer) %>
        </p>
    <% end %>
    <p>
        <%= f.submit 'Submit'%>
    </p>
<% end %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>
 
<%= form_for :question, method: :get do |f| %>
    <div class="input-append">
      <%= f.autocomplete_field :title, autocomplete_question_title_questions_path, placeholder: "Search Question" %>
      <button class="btn" type="submit">Search</button>
    </div>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>To</th>
    <th>Status</th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= link_to "#{question.content}", question %></td>
      <td><%= question.answerer.name %></td>
      <% if not question.submitted %>
        <td><%= link_to 'Answer', edit_question_path(question) %></td>
      <% else %>
        <td> Submitted </td>
      <% end %>
      <td><%= link_to 'Delete', question_path(question),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1> Create a new question </h1>

<% if @question.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited
          this question from being saved:</h2>
        <ul>
            <% @question.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= nested_form_for @question do |f| %>
  <p>
    <%= f.label :to %><br>
    <%= autocomplete_field_tag 'user_name', '', '/users/autocomplete_user_name', :size => 75, :placeholder => "Search User" %>
  </p>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form_title" %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "form_content" %>
  </p>

  <h3> Answers: </h3>
  <%= f.fields_for :answers do |answer| %>
    <p>
        <%= answer.text_area :answer, :class => "form_answer" %>
        <%= answer.link_to_remove "Remove" %>
    </p>
  <% end %>
  <p><%= f.link_to_add "Add", :answers %></p>

  <p>
    <%= f.submit 'Create question', :class => 'btn' %>
  </p>
<% end %>

app/views/questions/show.html.erb
<p>
    <strong>From:</strong>
    <%= @question.owner.name %>
</p>
<p>
    <strong>To:</strong>
    <%= @question.answerer.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<% if @question.owner == @user %>
    <% @question.answers.each do |answer| %>
      <p>
        <% if answer.id == @question.selectedAnswer_id %>
            <img src="/images/selectedChoice.png">
        <% else %>
            <img src="/images/unselectedchoice.png">
        <% end %>
        <% if answer.correct %>
            <%= label_tag(:answer, answer.answer, :class => "correct_answer") %>
        <% else %>
            <%= label_tag(:answer, answer.answer) %>
        <% end %>
      </p>
    <% end %>
<% else %>
    <% if @question.answerer == @user %>
        <% @question.answers.each do |answer| %>
          <p>
            <% if answer.id == @question.selectedAnswer_id %>
                <img src="/images/selectedChoice.png">
                <% if not answer.correct %>
                    <%= label_tag(:answer, answer.answer, :class => "wrong_answer") %>
                <% else %>
                    <%= label_tag(:answer, answer.answer, :class => "correct_answer") %>
                <% end %>
            <% else %>
                <img src="/images/unselectedchoice.png">
                <%= label_tag(:answer, answer.answer) %>
            <% end %>
          </p>
        <% end %>
    <% else %>
        <%= button_to "Challenge this", { action: "create", id: @question.id, controller: "challenges" },
                                method: :post %>

    <% end %>
<% end %>