config/routes.rb
Askme::Application.routes.draw do
  get "home/index"
    get "sessions/create"
    get "sessions/destroy"
    get "welcome/index"
    
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    

    resources :sessions, only: [:create, :destroy]
    root 'home#index'

    resources :questions do
        resources :answers
        get :autocomplete_question_title, :on => :collection
    end
    
    resources :users, only: [:index] do
        get :autocomplete_user_name, :on => :collection 
    end

    resources :challenges
    resources :friendships, only: [:create, :destroy, :show, :update]

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user, dependent: :destroy
    belongs_to :friend, :class_name => "User", dependent: :destroy
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def show
        @user= current_user 
        @users = User.all
    end
    
    def create
        @friendship = current_user.friendships.build(:friend_id => params[:friend_id], :status => 'pending')
        if @friendship.save
            flash[:notice] = "Added friend."
            redirect_to friendship_path(current_user)
        else
            flash[:error] = "Unable to add friend."
            redirect_to friendship_path(current_user)
        end
    end
    
    def update
        @user = current_user
        @friend = User.find(params[:id])
        @friendship = Friendship.find_by_user_id_and_friend_id(@friend, @user)
        @friendship.update_attributes(:status => 'accepted')
        redirect_to friendship_path(current_user)
    end
    
    def destroy
        @friendship = current_user.friendships.find(params[:id])
        @friendship.destroy
        flash[:notice] = "Removed friendship."
        redirect_to friendship_path(current_user)
    end
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/views/friendships/show.html.erb
<h1> Friends </h1>

<h2> All friends </h2>
<ul>
    <% for user in @users %>
    <li>
        <%=h user.name %>
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
    </li>
    <% end %>
</ul>


<h2> Your friends </h2>
<ul>
    <% for friendship in @user.friendships %>
        <% if friendship.status == 'accepted' %>
            <li>
                <%=h friendship.friend.name %>
                (<%= link_to "remove", friendship, :method => :delete %>)
            </li>
        <% end %>
    <% end %>
    <% for friendship in @user.inverse_friendships %>
        <% if friendship.status == 'accepted' %>
            <li>
                <%=h friendship.user.name %>
                (<%= link_to "remove", friendship, :method => :delete %>)
            </li>
        <% end %>
    <% end %>
</ul>

<h2>Pending request</h2>
<ul>
  <% for user in @user.pending_friends %>
    <li><%=h user.name %></li>
  <% end %>
</ul>

<h2>Requested friends</h2>
<ul>
  <% for user in @user.requested_friends %>
    <li>
        <%=h user.name %>
        <%= link_to '[Accept]', friendship_path(:id => user), :method => :put, :confirm => 'Accept friend request! Are you sure?' %> |
        <%= link_to '[Reject]', friendship_path(:id => user), :method => :delete, :confirm => 'Reject friend request! Are you sure?' %>
    </li>
  <% end %>
</ul>