config/routes.rb
Askme::Application.routes.draw do
  get "home/index"
    get "sessions/create"
    get "sessions/destroy"
    get "welcome/index"
    
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    

    resources :sessions, only: [:create, :destroy]
    root 'home#index'

    resources :questions do
        resources :answers
        get :autocomplete_question_title, :on => :collection
    end
    
    resources :users, only: [:index] do
        get :autocomplete_user_name, :on => :collection 
    end

    resources :challenges
    resources :friendships, only: [:create, :destroy, :show, :update]

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
    
    def index
        @questions = Question.where(answerer_id: current_user.id).where(submitted: true).order("updated_at DESC")
        @status = Hash.new
        @questions.each do |q|
            if q.selectedAnswer_id
                @answer = Answer.find(q.selectedAnswer_id)
                if @answer.correct
                    @status[q.id] = 'Success'
                else
                    @status[q.id] = 'Fail'
                end
            else
                @status[q.id] = 'Answer'
            end
            @status[q.id]
        end
    end
    
    def create
        @user = current_user
        @question = Question.find(params[:id])
        
        # Verify if the current user is friend with the question owner
        if @user.friends.include?(@question.owner) or @user.inverse_friends.include?(@question.owner)
            #Create a new question by copying from old question
            @newQuestion = Question.create(title: @question.title, content: @question.content, owner_id: @question.owner_id, submitted: true, answerer_id: @user.id)
            for a in @question.answers do
                @answer = @newQuestion.answers.create( answer: a.answer, correct: a.correct )
            end    

            if @newQuestion.save
                redirect_to edit_challenge_path(@newQuestion)
            end
        else
            render 'questions/show'
        end
    end
    
    def edit
        @question = Question.find(params[:id])
        if @question.selectedAnswer_id
            redirect_to questions_path
        end
    end
    
    def update
        @question = Question.find(params[:id])
        @answer = Answer.find(params[:correct])
        @question.selectedAnswer_id = params[:correct]
        if @question.update(question_params)
            redirect_to @question
        else
            render 'edit'
        end 
    end
    
     private
        def question_params
           params.require(:question).permit(:title, :content, :answerer_id,
               answers_attributes: [:id, :answer, :question_id, :correct, :_destroy]) 
        end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/edit.html.erb
<h1> Answer your question </h1>

<%= form_for :question, url: challenge_path(@question), method: :patch do |f| %>
    
    <label>From:</label> 
    <p class="challenge_owner">
        <%= @question.owner.name %>
    </p>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title, :readonly => true, :class => "form_title" %>
    </p>

    <p>
        <%= f.label :content %><br>
        <%= f.text_area :content, :readonly => true, :class => "form_content"  %>
    </p>

    <% @question.answers.each do |answer| %>
        <p>
            <%= radio_button_tag("correct", answer.id, false) %>
            <%= label_tag(:answer, answer.answer) %>
        </p>
    <% end %>
    <p>
        <%= f.submit 'Submit'%>
    </p>
<% end %>

app/views/challenges/index.html.erb
<h1>Your challenges</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th> From </th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <% if not question.selectedAnswer_id %>
            <td><%= link_to "#{question.content}", edit_challenge_path(question) %></td>
      <% else %>
            <td><%= link_to "#{question.content}", question %></td>      
      <% end %>
      <td><%= question.owner.name %></td>
      <% if not question.selectedAnswer_id %>
            <td></td>
      <% else %>
            <% if @status[question.id] == 'Fail' %>
                <td class="challenge_fail"> <%= @status[question.id] %> </td>
            <% else %>
                <td class="challenge_success"> <%= @status[question.id] %> </td>
            <% end %>
      <% end %>
    </tr>
  <% end %>
</table>