config/routes.rb
Askme::Application.routes.draw do
  get "home/index"
    get "sessions/create"
    get "sessions/destroy"
    get "welcome/index"
    
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    

    resources :sessions, only: [:create, :destroy]
    root 'home#index'

    resources :questions do
        resources :answers
        get :autocomplete_question_title, :on => :collection
    end
    
    resources :users, only: [:index] do
        get :autocomplete_user_name, :on => :collection 
    end

    resources :challenges
    resources :friendships, only: [:create, :destroy, :show, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Askme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "nested_form" %>
  <%= javascript_include_tag "application", "autocomplete-rails.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if current_user %>
        <header class="extendfull">
            <nav> 
                
                <%= link_to "Home", controller: "welcome" %>
                <%= link_to "Your questions", controller: "questions" %>
                <%= link_to "New question", new_question_path %>
                <%= link_to "Your challenges", controller: "challenges" %>
                <%= link_to "Friends", friendship_path(current_user) %>
                
                <div class="login">
                    <% if current_user %>
                        <strong><%= current_user.name %></strong>
                        <%= link_to "Sign out", signout_path, id: "sign_out" %>
                    <% else %>
                        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
                    <% end %>
                </div>
            </nav>
        </header>
    
        <%= form_for :question, method: :get do |f| %>
            <div class="input-append">
              <%= f.autocomplete_field :title, autocomplete_question_title_questions_path, placeholder: "Search Question" %>
              <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
                   of using a Rails form helper -->
              <button class="btn login_button" type="submit">Search</button>
            </div>
        <% end %>
                
    <% end %>
    
    <br>
    <br>
    <section class="main_middle">
        <%= yield %>
    </section>
</body>
</html>